name: Deploy

on:
  ###push:
  ###  branches: ["main"]
  # Allowed to run manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Run deploy command set
        run: |
          ls -R -l -h
          git config user.email "githubAction@yui-Kitamura.github.io"
          git config user.name "Github Action"
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          npm ci
          npm install gh-pages
          npm run deploy
