name: Deploy

on:
  push:
    branches: ["main"]
  # Allowed to run manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ls -R -l -h
      - run: npm run deploy
